name: Generate GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # 매일 0시 자동 업데이트
  workflow_dispatch:               # 수동 실행도 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # 출력 파일명 (원하는 이름으로 변경 가능)
          filename: metrics.plugin.isocalendar.fullyear.svg

          # 토큰
          token: ${{ secrets.METRICS_TOKEN }}

          # 기본 정보 제외하고 깔끔하게
          base: ""

          # 플러그인 활성화
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
